name: Test, Build Docker Image, and Update Config Repo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Build React app
      run: |
        npm run build

    - name: Build Docker image
      run: |
        docker build --tag mohamedmagdykhamis/todo-app:${{ github.sha }} .

  publish-and-update:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: mohamedmagdykhamis/todo-app:${{ github.sha }}

    - name: Update Config Repo
      run: |
        echo "promoting into dev environment!"
        git config --global user.email actions@github.com && git config --global user.name GitHub Actions
        echo "cloning config repo argocd-react-manifest"
        git clone https://oauth2:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository_owner }}/argocd-react-manifest.git
        cd argocd-react-manifest
        echo "checkout main branch"
        git checkout main
        echo "Updating Image tag in values.yaml file"
        sed -i "s,image:.*,image: mohamedmagdykhamis/todo-app:${{ github.sha }}," reactapp/values.yaml
        git add . && git commit -m "Updated Image tag to ${{ github.sha }}"
        git push
